---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dnspod-secret
  namespace: cert-manager
spec:
  encryptedData:
    secretId: AgCQQmex5LcQU8aj1nY1q2DhbGP7hbKHOjDKxKl5ocGFe3QwW+fYjzBS3Nlv6gaT4MGEgfGNw+zX7tsxpl+j1xsOOa7lnM5z94kNFU0ty36WqOw7ZOrThki6NdRIb2LAy0zqXmygi4BBvFDX1gjvSDw7Cgt3x7PECTVnlxYPrMzLqzR9J9YB55MHV88uUNukgR65oCas321LQMe5Pf6sp9Pv8HvMM6MPFqieFeJz2BJbVlpqwfeyhhUALHzwQbutiX4Lv6vTv8XdzqLeZQiWDqYGQuPuRfMw7c0YP5mh6XlMZnDGwsJ4yQdzbKsV40fnCIpDoJThzVieR2OR3kqnDPI0iSXuLiWdFoaHOdAu6FY8W6nr8hSm5NIOvwaaKCiS1idGmZ/ob3aeUIGtC3JeiKwWr51mV6oG+n9HxyFQIuRz9uD5nJcesist8OLer+djyEiyLJCOJZ8KYJkxQuF1y7tHGrbtMTfQOHpK4OM7Sl2ZflPRUG4YU0srRGEVQUq2yiICWbCF/ZVSLDQrlQ+dPW9AzaIdrn3VGASZmOuNbUH1YCms4TU2LS1fJxkzPDs78w2E1LIzpgmiGoMPMqo1MJxZyOMSSJ6NSUilZ/BHQN9aubChfHfD7NOW/uSGpsVXtWjOC8ahJcQyHGbB1f7SmQhPFPhE3V/pNZ+Cq8t9rTbS9e7urqaXuJvpE2SqW2BlmMIGFMpH9eXMtTHICGT4bTlTyP1KSsk1a3ebuua1+uvt+zbAyCE=
    secretKey: AgCsR4G0thjuzTAF2TD6LOXvxP9mTFLqTXiti2pqy6l7xxwTZ3tAq6tO1RII7pAXqy6OYAw+DCGLa8qSjGWOaUKKtV1u2Xn6QQ7IpvykV6YrE03we2IgczjrCrje0qIkWcd7WaCTODu8vJd9qE4PpUILzJOy/7Y+VTII7ZEpFQhkBPUO7wnxvw+VWLgPPsiFCQxysmNQkpV0wpEHnkY5geJhz4Kxzv/48Ety+mekSgmuI5KnBY1Qj3Xryhy1Rw8fsmWv56iDS5qWuazNLAiwnMToIT6uwgDhjGMmwptiG8Ed6hXdEaNnxWYrKEzWZcwnFXs/6iBL5mMr2Qpon2uoDMwBh+tx7Vec6CUq1aQmgNlUvoJd8hDtzOYLxbybHJYNo8Y2jN252MFTAACSSR3Nk+7aWx1UVMoCcsHYDzxCmNYfZdTu5uEhGC0jc20a0bBxELKqLHby0NkhLAvp6uiwY/mXhT28dzSa11Jt6owrnRCwwFUBq5DLTY9uetxxgyatQh/7UqWQm7jH1gcd0eMWhfPtfYvV+bMXSrdUvD5funa4xciwUEqnupkvSHtvEnqGIkDKwd6VaToEqfJPb5Vxt5ke1rAbnldkiPdAOhf/n8zMJ6wbBNUzFZBTtFAmqxtWTZhInBGN7oTk5O7lAeP0MhGDq1th21cQ79odUKdK6cMuNP/wAg7tMLY9ahgVYaQ8icqDyTowc0ZdqEWmcvZaM4HHDj88j7yHdn5+fsBDinYtEw==
  template:
    metadata:
      name: dnspod-secret
      namespace: cert-manager
