---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dnspod-secret
  namespace: cert-manager
spec:
  encryptedData:
    secretId: AgChohk6DkfElM3kyuydfBDb15Ck9iQVmEpuUSwr9HiHrr+vCIVr0fgH46rO2ew7bTCpNgSPYpKQ2422bFj/clmtS3tiSkGo+fCjLJfI4eCakOHM5XBzWO1heZkkc6IGw47Vz/XHI4cG5gqVVftAGELYX+ZzogQ20XfXF5JzKt+L5EQJRneUQwLtrJ9INpUP5QYGvP/c7EF10TsIiY+zMJfN+wRIjTQVKONVowfdgPFxTCawmWACOJH74/vSrV5AU0HaUa6RdzsCyGUrG+Utht3UWqvpeRnRzxqthw0iHjC/9zWe62RRzWdJ8gPlNMfHT6YXXQ2zv0sjanszA0pZcMjv12qCSzenfrWc6dlU37lDqAy+7MUleXym93OE3yDe5Ii9lc0uhqcwUg77PCYX3ScLpVXXvumxssdCM/qnWdyQJXPjhw/Sti0NLYZnUEd8jHcF0wwUlx3JmtG3tyvtUMczD0wwRaHdT8P1ezEHQjxkp7RCsHCVQGuiJTcw/obv/L8TMoQMq5RsHj6repgWWGJdBQcaKgurbTGdC8K3S41yXWijqXUoD58QiwE7qalV8XtNNjuw3Dfd0Uy9nKcDRbEDVSk9PjvW0Onmu0gsCZDWl9K4+ze+LkxHjv58YbyD+Mqbub1WDFV2gxs42QH4kVWDTh+UbkAMSGU2LTWASCafELvBWQsNdwcYBKn5rP3BUtzArs5ekI9GcCsDhN6OYqPt+2MDGu8yE4hS5fKLF3mhFQxQl3g=
    secretKey: AgA3dKZJeRCXpRHApSagftzFwTxR/yGG+41cqCZUUuVuTg+9vd+PBmh82A811hi2qSJDEzPIHZqxcCj0E2Bd3eY+xUGTnVAuJBSrv+l2eRqFgJ/5S064DdOPhWbBXYskTEUBreqNIWGYG7DmRPLWCcpP1CiSnR4AGP8z9euG15Cl/5sZjm/bl3hyGWNmFjHIsVYsPj1t/QigRm/5NNgqBefId3dDvXBQNNLf35fXCTBZV1/9qGa336cbF1Yi97kwgT1ytdvMTx/s2B8Aw/lwRccD1NdQUL0VjGFhx7O3hqAB0QnTtT/ZVJ44HmIkp8oy3HCSkJpoBe0noM2mE8tKH5LNLJPnetRCdoHbuG/Pkas3np5SsR25gNIqXzkartpvQziQs0yCgwXYnMAcOwd585t8Rh0BfigNJ7L2DjjVAKR3IghQUclYTYBmlM1NPBFEonu+Fkw1svuDNacp6o4jjmPQAf1mk+sLfwBqSpP1858UNiqHM3UKVw04WaPpx7z5BzqAbEmSv+5iukn93EIU0DcB4F+wNVWFRRMSZrlbC85WOet+0nfiNxCUJU9UgqgMxomQEndQtXL035n2tO6yofFPFnG/wWh1sWpUNZ4MJLUoKmzgc7o2QGmVA0SzyD01XprpQSuQHjHVYJFFuxJ/yeBhZbqjgza7xONsiRCmIMc7bogGF6/oWGVuz0LF1vFV1h+IAy76OxDy9XMviYvzgET9gA2Ov0pdW1MZDUL+VxSrcA==
  template:
    metadata:
      creationTimestamp: null
      name: dnspod-secret
      namespace: cert-manager
    type: Opaque
